"""Honesty-gap comparison: queue-aware fills vs naive instant fills.

Runs the same strategy twice — once with `ProbabilisticQueueModel`
(realistic, queue-aware) and once with `InstantFillQueueModel` (the
implicit assumption in vectorised backtesters). The PnL delta is the
"honesty gap": the cost you'd ignore by trusting a vectorised result.
"""
from __future__ import annotations

from collections.abc import Callable, Iterable
from dataclasses import dataclass

from obscura.book.types import BookEvent
from obscura.sim import InstantFillQueueModel, Latency, ProbabilisticQueueModel, SimResult, run
from obscura.sim.types import Strategy


@dataclass
class HonestyGapReport:
    """Side-by-side comparison of two queue models' results."""

    naive: SimResult
    queue_aware: SimResult
    symbol: str
    strategy_name: str

    @property
    def pnl_naive(self) -> int:
        return self.naive.cash_change

    @property
    def pnl_queue_aware(self) -> int:
        return self.queue_aware.cash_change

    @property
    def pnl_gap(self) -> int:
        return self.pnl_naive - self.pnl_queue_aware

    @property
    def pnl_gap_dollars(self) -> float:
        return self.pnl_gap / 10000.0

    @property
    def fill_count_naive(self) -> int:
        return len(self.naive.fills)

    @property
    def fill_count_queue_aware(self) -> int:
        return len(self.queue_aware.fills)

    @property
    def shares_naive(self) -> int:
        return sum(f.shares for f in self.naive.fills)

    @property
    def shares_queue_aware(self) -> int:
        return sum(f.shares for f in self.queue_aware.fills)

    def to_markdown(self) -> str:
        return _render_markdown(self)


def compare_queue_models(
    events_factory: Callable[[], Iterable[BookEvent]],
    strategy_factory: Callable[[], Strategy],
    *,
    symbol: str,
    strategy_name: str,
    latency: Latency | None = None,
) -> HonestyGapReport:
    """Run the same strategy twice on the same event stream, two queue models."""
    latency = latency or Latency()

    naive = run(
        events_factory(),
        strategy_factory(),
        symbol=symbol,
        latency=latency,
        queue_model=InstantFillQueueModel(),
    )
    queue_aware = run(
        events_factory(),
        strategy_factory(),
        symbol=symbol,
        latency=latency,
        queue_model=ProbabilisticQueueModel(),
    )
    return HonestyGapReport(
        naive=naive,
        queue_aware=queue_aware,
        symbol=symbol,
        strategy_name=strategy_name,
    )


def _render_markdown(rep: HonestyGapReport) -> str:
    naive_pct = "" if rep.pnl_queue_aware == 0 else (
        f" ({100.0 * rep.pnl_gap / abs(rep.pnl_queue_aware):+.1f}% vs queue-aware)"
    )
    return f"""# obscura honesty-gap report

**Symbol:** `{rep.symbol}`  ·  **Strategy:** `{rep.strategy_name}`

Same strategy. Same event stream. Two queue models.

| Metric | Naive (instant fill) | Queue-aware (Cont 2010) | Gap |
|---|---:|---:|---:|
| Realised PnL ($) | {rep.pnl_naive / 10000.0:>+,.2f} | {rep.pnl_queue_aware / 10000.0:>+,.2f} | **{rep.pnl_gap_dollars:>+,.2f}**{naive_pct} |
| Fills | {rep.fill_count_naive} | {rep.fill_count_queue_aware} | {rep.fill_count_naive - rep.fill_count_queue_aware:+} |
| Shares filled | {rep.shares_naive:,} | {rep.shares_queue_aware:,} | {rep.shares_naive - rep.shares_queue_aware:+,} |
| Inventory at end (shares) | {rep.naive.inventory:+,} | {rep.queue_aware.inventory:+,} | — |

> generated by `obscura analyze honesty-gap`
"""
